apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubetasker-controller.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetasker-controller.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "kubetasker-controller.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager