apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubetasker-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetasker-controller.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8090 }}
      protocol: TCP
      name: http
  selector:
    {{- include "kubetasker-controller.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager