apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubetasker-controller.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetasker-controller.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "kubetasker-controller.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager