{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubetasker-frontend.serviceAccountName" . }}
  labels:
    {{- include "kubetasker-frontend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubetasker-frontend.fullname" . }}
  labels:
    {{- include "kubetasker-frontend.labels" . | nindent 4 }}
rules:
- apiGroups: ["task.ktasker.com"]
  resources: ["ktasks"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubetasker-frontend.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubetasker-frontend.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kubetasker-frontend.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}