apiVersion: custom.custom.io/v1
kind: JobRequest
metadata:
  labels:
    app.kubernetes.io/name: kubetasker
    app.kubernetes.io/managed-by: kustomize
  name: jobrequest-sample
spec:
  # TODO(user): Add fields here
