apiVersion: custom.custom.io/v1
kind: JobRequest
metadata:
  labels:
    app.kubernetes.io/name: jobrequest
    app.kubernetes.io/managed-by: kustomize
  name: jobrequest-sample2
spec:
  image: busybox:1.28
  command:
    - "echo"
    - "Hello from my second custom resource!"
