apiVersion: custom.custom.io/v1
kind: Ktask
metadata:
  labels:
    app.kubernetes.io/name: ktask
    app.kubernetes.io/managed-by: kustomize
  name: ktask-sample
spec:
  image: busybox:1.28
  command:
    - "echo"
    - "Hello from my first custom resource!"
